### ISSUE TITLE
Comments/typos for https://qc2-teaching.readthedocs.io/en/latest/programming.html

### ISSUE THREAD

**Issue by Beliavsky** [grimme-lab/qc2-teaching#35]
For some reason I am allergic to pull requests. Here are some comments about https://qc2-teaching.readthedocs.io/en/latest/programming.html . Thanks for writing it.

"The intrinsic :: selected_real_kinds declares"

should be selected_real_kind (no trailing s).

"we will always declare all the intrinsic functions we are using here such that you know they are, indeed, intrinsic functions."

That is a matter of style. I would find it tedious to declare log, exp etc. as intrinsic.

"descriminant" should be spelled "discriminant"

I would write `var.lt.3` as `var .lt. 3` so it does not look component selection as in other languages.

"To negate a logical expression we use prepend .not." should be

"To negate a logical expression we prepend .not."

Add a write in code to get

```
program cumulative_sum
  implicit none
  integer :: i, n
  integer :: number
  ! initialize
  number = 0
  write (*,*) "enter an integer"
  read(*, *) n
  do i = 1, n
    number = number + i
  end do
  write(*, *) "Sum is", number
end program cumulative_sum
```
For the "sum even numbers" code I would have introduced a loop with a stride

`do i=2, n, 2`

"Programmers coming from almost any language might find it confusing to start counting at 1."
I think you are underselling Fortran here :). R, Matlab/Octave, Julia all have 1-based indexing.

The label for the line of code

`write(*, *) "Maximal/minimal value at", maxval(vec), minval(vec)`

is misleading. It prints the max and min values, not their locations, for which you would use maxloc and minloc. Same comment for code array.f90.

"write out side" should be "write outside"

Again in sum_func.f90 there reads without prompt for what the user should enter.

You write 

"There are cases were we do not want to return a value, in this case we would return nothing, functions of this kind are called subroutines" but the code below it does have an intent(out) variable. Maybe change it to print the sum in the subroutine instead of having an intent(out).

"On the other hand, if the code in the subroutine gets more complicated and the number of dummy arguments grows, we should prefer subroutines, because they are more visible in the code, especially due to the explicit call keyword."

It's fine to have a function with many arguments. The key point of subroutines is that they can any number of outputs through their arguments.

One "r" in "preferrably" and "preferrable".

"like its done for fname" should be "as is done for fname"

**Comment by awvwgk** [comment]
Thanks for catching those typos and the helpful feedback.

As teachers we are constantly lying to our students, or at least not telling them the whole truth ;).

> "we will always declare all the intrinsic functions we are using here such that you know they are, indeed, intrinsic functions."
>
> That is a matter of style. I would find it tedious to declare log, exp etc. as intrinsic.

Students don't know whether a function is intrinsic or not at this point. By declaring them in the examples I try to document the available intrinsics as well as ones I'm using for each snippet. Editor highlighting of course reveals that those names are special, still extra verbosity at the beginning can be helpful.

> For the "sum even numbers" code I would have introduced a loop with a stride
>
> `do i=2, n, 2`

Sure, also an option, however I want to introduce `cycle` and the modulo functions with this example :). Maybe I should get a better example. Also, I just noticed I never introduce strides for loops here.

> Again in sum_func.f90 there reads without prompt for what the user should enter.

At this point I'm expecting students to do prompts themselves. Prompting is introduced early in examples and exercises and dropped later to keep the snippets concise. The comments for each read could of course be shown as prompts.

> "Programmers coming from almost any language might find it confusing to start counting at 1."
> I think you are underselling Fortran here :). R, Matlab/Octave, Julia all have 1-based indexing.

Of course, there are other languages with use 1-based indexing. Most students with programming experience usually know about Python, C++ or Java at this stage of their studies. We could make it more concrete and mention a few of the common languages using exclusively 0-based indexing here.

> "There are cases were we do not want to return a value, in this case we would return nothing, functions of this kind are called subroutines" but the code below it does have an intent(out) variable. Maybe change it to print the sum in the subroutine instead of having an intent(out).

I was thinking in C logic when I wrote this, *i.e.* returning `void` is a subroutine rather than a function in Fortran. At this point I have to introduce the difference between functions (the latter were used for quite a while as intrinsics) and subroutines (now needing a `call` statement). I wonder whether there is better way to motivate having subroutines over functions with a simple example.

**Comment by awvwgk** [comment]
I'll have the teachers for this semester have the final choice on the remaining points.

**Comment by Beliavsky** [comment]
The example code I used to tweet about subroutines, which you are welcome to use, is below. Often you want to compute the mean and standard deviation to describe data, and since the mean is needed to compute the standard deviation, it makes sense to use a subroutine to compute both. Since the calculation of skew and kurtosis depend on the mean and sd, they would be good candidates for optional arguments.

```
! Define and call a subroutine
program optional_arg
implicit none
real :: x(1000000),xmean,xsd
call random_seed()
call random_number(x)   ! generate uniform random deviates on (0,1]
call stats(x,xmean,xsd) ! subroutine invoked with the call statement
print*,xmean,xsd
contains
!
pure subroutine stats(x,xmean,xsd)
real, intent(in)  :: x(:)  ! data for which stats computed
real, intent(out) :: xmean ! mean of x(:)
real, intent(out) :: xsd   ! standard deviation of x(:)
real, parameter   :: bad = -999.0
integer           :: n
n     = size(x)
! set outputs to bad value if there is insufficient data
xmean = bad
xsd   = bad
if (n < 1) return
xmean = sum(x)/size(x) ! enough data to compute mean
if (n < 2) return
xsd = sqrt(sum((x-xmean)**2)/(n-1)) ! enough data to compute standard deviation
end subroutine stats
end program optional_arg
```

**Comment by marcelmbn** [comment]
> "There are cases were we do not want to return a value, in this case we would return nothing, functions of this kind are called subroutines" but the code below it does have an intent(out) variable. Maybe change it to print the sum in the subroutine instead of having an intent(out).

I modified the motivation for using subroutines in a way that the aforementioned conflict is not present anymore.
